sources:
  - url: https://fs.blog/first-principles/
    tags: []
    status: scraped
    added_at: 2026-01-15T15:18:34.210Z
    scraped_at: 2026-01-15T15:18:50.294Z
  - url: https://fs.blog/circle-of-competence/
    tags: []
    status: scraped
    added_at: 2026-01-15T15:18:34.211Z
    scraped_at: 2026-01-15T15:18:50.936Z
  - url: https://fs.blog/inversion/
    tags: []
    status: scraped
    added_at: 2026-01-15T15:18:34.211Z
    scraped_at: 2026-01-15T15:18:51.490Z
